### ISSUE TITLE
In translationWords Article the links under Bible References gives pop up error

### ISSUE THREAD

**Issue by danielklapp** [unfoldingWord/gateway-edit#529] opened 2023-08-25 18:09 UTC
https://release-v2-1-0--gateway-edit.netlify.app/
v2.1.0 build ad1df2f QA
Org:unfoldingWord, lang :en
Steps to reproduce: 
- Opened Matthew 1:1
- Go to translationWords Article and scrolled down to Bible References:
- When clicking on any of the reference links a pop up error appears and in the console it gives useResourceClickListener() error parsing link and Uncaught (in promise) Error.
- DOD When clicking on this link we should see a pop up of this verse or reference range in the current gateway language. 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdVU5IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--b1ff18daeb49e5a2158ca91145c6242226fc5d35/Screenshot%202023-08-25%20at%209.34.36%20AM.png)

**Comment by PhotoNomad0** [comment] 2023-08-28 15:20
See this issue for reference: https://github.com/unfoldingWord/gateway-edit/issues/391

**Comment by PhotoNomad0** [comment] 2023-08-28 15:24
@danielklapp Is this a duplicate of https://github.com/unfoldingWord/gateway-edit/issues/369 ?

**Comment by danielklapp** [comment] 2023-08-28 15:43
> @danielklapp Is this a duplicate of #369 ?

@PhotoNomad0 yes it appears to be a duplicate.

**Comment by birchamp** [comment] 2023-10-18 18:42
Yes this is a duplicate of #369

**Closed by birchamp** 2023-10-18 18:42 UTC
Labels: Priority/Low, duplicate
