### ISSUE TITLE
Add email validation to feedback form

### ISSUE THREAD

**Issue by mannycolon** [unfoldingWord/gateway-edit#198] opened 2021-05-13 02:48 UTC
Issue:
---
When a user enters their email address into the feedback form the email address should be checked for proper formatting as an email address in case the user mis-entered the address. The user should be notified to: "Please enter a valid email address" and prevented from submitting feedback. 

DoD:
---
Entering a malformed email address in the feedback form results in a notification and prevents the user from submitting the form.

Details:
---

**Comment by BincyJ** [comment] 2021-05-13 17:59
TBC  how to handle missing email ID information - Need error message

**Comment by PhotoNomad0** [comment] 2021-08-12 14:58
duplicate of https://github.com/unfoldingword/gateway-edit/issues/106

**Closed** 2021-08-20 09:26 UTC
Labels: Priority/Low, duplicate, Blocked
