### ISSUE TITLE
Unable to merge ULT in some cases

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/gateway-edit#547] opened 2023-09-18 20:10 UTC
When edits are made to the ult and then the ust - then saving and merging them at same time. On a repeated process,   sometimes  it only shows the ust as available to merge - not the ult.
- Testing the merge function in gWE, I found that on a fresh start, I edited UST and ULT on the same book, same chapter/verse and saved both the cards and did a merge to master. 
-  I continued editing another verse in ULT and UST and saved my changes. When I tried to merge again to master, ULT wont show in the merge resources checklist. That made me confused cause I edited and saved. The new changes can be found in my user branch, but it wont allow me to merge to master.

### Testing Instructions

See: https://github.com/unfoldingWord/gateway-edit/pull/594#issue-2012429771

**Comment by PhotoNomad0** [comment] 2023-09-19 14:33
@kintsoogi It looks like we are checking before the branch status has been updated.  It seems we need to wait until later  to check the merge status - checking after we get an updated file sha should be safe.

**Comment by birchamp** [comment] 2023-09-19 23:39
@PhotoNomad0 @kintsoogi @elsylambert  Does the merge update the branch after merge the way that tCC does?

**Comment by elsylambert** [comment] 2023-09-19 23:46
Here, the merge updates the master branch and user branch automatically
gets deleted, same like tCC.

**Comment by PhotoNomad0** [comment] 2023-09-20 12:25
> @PhotoNomad0 @kintsoogi @elsylambert Does the merge update the branch after merge the way that tCC does?

@birchamp It seems to be more of a timing issue - that GWE is checking too soon.  We don't continually poll the status, but we can delay when we check after doing a save.

**Comment by PhotoNomad0** [comment] 2023-09-20 20:19
@kintsoogi OK - I was having trouble reproducing it again, but when I did I saw that the mergeable state was false for the ULT, but not the UST. But when checked later it showed as mergable.  Again it seems to be a timing issue.

<img width="2513" alt="Screenshot 2023-09-20 at 3 32 27 PM (2)" src="https://github.com/unfoldingWord/gateway-edit/assets/14238574/57527d68-c66e-460c-b263-58d8320fafcb">

**Comment by richmahn** [comment] 2023-09-21 16:03
@PhotoNomad0 A branch becomes in "conflict" mode if it is being currently processed by Gitea at the time of your PR GET query. So yeah, a quick PR check will return "mergeable: false" but later will be true again.

**Comment by theNerd247** [comment] 2023-10-06 14:56
@PhotoNomad0 @richmahn. @kintsoogi And I have spent some time digging into this issue. We've discovered the following: 
1. we are making an API call to _create_ a PR everytime we want to check the status of a particular PR. I'm not sure if this was done by design. 
2. we are making duplicate API calls (to create a PR) everytime the content is saved - I believe only 1 call should be made.
3. we have an initial state problem. The following steps seem to be a way to replicate the issue deterministicallly
  1. ensure no user branch exists
  2. modify some text
  3. save the edit (this creates a user branch and a PR)
  4. repeat step 2 and 3 multiple times. There should be no merge conflicts available
  5. refresh the webpage
  6. repeat step 2 and 3. There should now a be a merge conflict for that particular card

**Comment by birchamp** [comment] 2023-10-24 17:03
@richmahn we're really going to need your help with the above ^^

**Comment by richmahn** [comment] 2023-10-25 20:39
@birchamp Thanks. Noah just alerted me to this on Discord in a DM. Still not sure how to remember to look in the Github inbox on here often. I should just do that.

**Comment by richmahn** [comment] 2023-10-25 20:40
This is very interesting that it can't give you a reliable response.

**Comment by richmahn** [comment] 2023-10-25 20:49
Mine keeps looping and says true, unless I save to my branch, which gives a correct false because a branch that is being processed for a commit to be added can't be merged, understandably (you'd lose the commit).

**Comment by richmahn** [comment] 2023-10-25 21:04
Remember, mergeable flag does NOT necessarily mean it is conflicting, but just if that user at that time can merge it. Unable to merge due to a conflict is only ONE reason mergeable would be false.

I confirmed this. I sent a simple PUT to https://qa.door43.org/api/v1/repos/unfoldingWord/en_tq/contents/README.md

With this payload (correct SHA):
```
{
  "branch": "richmahn-tc-create-1",
  "content": "SGVsbG8gV29ybGQh",
  "message": "test from postman",
  "author": {},
  "sha": "87cacddaa0a172ea47c2f25eca1b1ceecdf5bb72"
}
```

It properly set mergeable to false during the translation.

**Comment by richmahn** [comment] 2023-10-25 22:33
But yes, I have to admit, while I realize this is how it works, that split second or two that it is false is really worthless. I'm going to dig into how the UI figures out a branch/PR is in conflict and if it would also give a false negative to the branch being in conflict. I **ASUME** if you were to actually go through with the merge, and at that very moment "mergeable" was false, it would just wait until that transaction is done to handle yours.

**Comment by richmahn** [comment] 2023-10-25 22:55
Interestingly in the UI it says this instead when I hit the PR page at the same time I use the API to commit content:

<img width="1072" alt="image" src="https://github.com/unfoldingWord/gateway-edit/assets/2839925/9154bba9-b1b8-4164-be08-1de1e5096fa2">

**Comment by richmahn** [comment] 2023-10-25 23:17
Ok, looking at the code, here are all the things that must be true for mergeable to be true:

```pr.Status != PullRequestStatusChecking && pr.Status != PullRequestStatusConflict && pr.Status != PullRequestStatusError && !pr.IsWorkInProgress()```

**Comment by richmahn** [comment] 2023-10-26 00:50
I was wondering why the API GET response of a PR doesn't show files conflicting, I realized this was due this:

```
Given we don't expose which files are conflicting with base branch(which is gitea's internal check to determine conflicting PR's) they don't have any other way to determine if a PR is conflicting with base branch.
```

Ugh. Yet you can know if conflicting at least.

**Comment by richmahn** [comment] 2023-10-26 01:37
@kintsoogi @theNerd247 @birchamp I find the only solution is if I expose the same info the UI had in the API, if there are conflicts and which files. Since we deal with public repos only anyway, best we do that. The properties will be:

has_conflicts: true|false
files_conflicting: []string

**Comment by theNerd247** [comment] 2023-10-26 15:33
Rich what would `has_conflicts: true, files_conflicting: []` mean? Wouldn't we only need `files_conflicting : []string`(no `null`) field to encode the same info?

**Comment by richmahn** [comment] 2023-10-26 17:10
Sure, could have just one, but figured it was also better to have a boolean there. We may find listing files is not the most reliable, for example, when a file is renamed or deleted. The PR model has these two properties.

**Comment by theNerd247** [comment] 2023-10-26 17:22
Hmmm...my only concern is how we handle non-valid states. in the case I presented would the lack of conflicting files indicate a bug on gitea or would would the `true` be the bug because no files were presented?

**Comment by richmahn** [comment] 2023-10-27 16:04
@theNerd247 So what do you suggest I add?

**Comment by richmahn** [comment] 2023-10-27 16:14
Basically you would check "HasConflicts". If true, which would be valid state since this solely means there are conflicts. Then you tell the user it can't be merged. If you want to tell the user which files had conflicts, you can list those in the ConflictedFiles array.

**Comment by theNerd247** [comment] 2023-11-07 14:48
Linking with #551 as both point to the same underlying issue.

**Comment by richmahn** [comment] 2023-11-14 21:16
@theNerd247 @kintsoogi @PhotoNomad0 

Here's what I have now with the latest fields added to the PR Response object:

I now have "Status" and "ConflictedFiles" in the PR response object. If I run 
```
while true; do curl -s "https://qa.door43.org/api/v1/repos/unfoldingWord/en_tq/pulls/184" | jq -r '{"mergeable": .mergeable, "status": .status, "conflicted_files": .conflicted_files}'; done
```
in my terminal, and then make a change to my tq branch, I get this:

```
...
{
  "mergeable": true,
  "status": "MERGEABLE",
  "conflicted_files": null
}
{
  "mergeable": false,
  "status": "CHECKING",
  "conflicted_files": null
}
{
  "mergeable": true,
  "status": "MERGEABLE",
  "conflicted_files": null
}
...
```

If I make a conflicting change to master at the same place:

```
...
{
  "mergeable": true,
  "status": "MERGEABLE",
  "conflicted_files": null
}
{
  "mergeable": false,
  "status": "CHECKING",
  "conflicted_files": null
}
{
  "mergeable": false,
  "status": "CHECKING",
  "conflicted_files": null
}
{
  "mergeable": false,
  "status": "CONFLICT",
  "conflicted_files": [
    "tq_MAT.tsv"
  ]
}
...
```

If I then make another edit in my TQ branch:

```
...
{
  "mergeable": false,
  "status": "CONFLICT",
  "conflicted_files": [
    "tq_MAT.tsv"
  ]
}
{
  "mergeable": false,
  "status": "CHECKING",
  "conflicted_files": [
    "tq_MAT.tsv"
  ]
}
{
  "mergeable": false,
  "status": "CONFLICT",
  "conflicted_files": [
    "tq_MAT.tsv"
  ]
}
...
```

So you can see status flips back to "CHECKING" and returns to "CONFLICT"

**Comment by richmahn** [comment] 2023-11-14 21:27
@theNerd247 More thoughts on our conversation yesterday:

We need to keep in mind that Gitea, when it gets the actual merge request, it will still use its own logic to determine if it can be merged when the POST request is made, before doing the git command, and then report any error for the latter. So despite what we determine is mergeable or not, Gitea still has the final say and action....thus its "interpretation" trumps all others. 

So going by what Gitea determines is mergeable in the end is something our apps need to know. The problem is that mergeable == false doesn't mean there is a failure, so we do have to also look to see if status == "CHECKING". (Github does this by setting mergeable to null! Not sure if better nor why Gitea, a Github clone, doesn't do that). And Gitea will wait to do an actual merge for status to go from "CHECKING" to any other status before checking if it can now merge, if we set the "merge_when_checks_succeed" when making the POST.

**Comment by richmahn** [comment] 2023-11-14 21:37
Also, it looks like when a merge request is sent and the status is "CHECKING" then it schedules an auto merge to be done in the background on the server when all checks are done and pass. I'm not sure what this will look like to the app / dcs-branch-merger! We may think it succeeded but didn't?

https://github.com/unfoldingWord/dcs/blob/50d6ddbda638dedc377ca2f829ae067099e571c2/routers/api/v1/repo/pull.go#L838

**Comment by richmahn** [comment] 2023-11-14 21:47
@theNerd247 Here is Gitea's ULTIMATE check for mergeable, which is called when a POST request is made to `pulls/{index}/merge` API endpoint.

https://github.com/unfoldingWord/dcs/blob/50d6ddbda638dedc377ca2f829ae067099e571c2/services/pull/check.go#L69

**Comment by richmahn** [comment] 2023-11-15 15:46
@theNerd247 I know you're trying to make a robust solution, which is good, but I want to suggest to not make this too complicated. We are just trying to warn the user if there are conflicts before hand so they don't think they can merge, and if there are, to tell them to contact their admin. It's better to error on them thinking it is mergeable (i.e. if status is checking, just assume there are no conflicts). We can do one last check when they are clicking on the "Merge my work" button to get the form, but ultimately the response from the server when the POST is made (the actual merge request) is where the magic/logic needs to happen if it was mergeable or not.

**Comment by theNerd247** [comment] 2023-11-15 16:17
Thanks for your update Rich! Thank you for your suggestion I have been keeping this in mind. 

Also, thank you for pointing out the code points where Gitea defines merge ability this helps a lot!

**Comment by elsylambert** [comment] 2023-11-29 22:37
Looks good in v2.2.0 build 7018555 QA. Merge my work shows the scripture resources in the list whenever there are changes that can be merged.

**Comment by danielklapp** [comment] 2023-11-30 14:43
Agree, looks good to me. Tested with v2.2.0 build 7018555 QA.

**Closed** 2023-12-15 14:57 UTC
Labels: QA/ElsyTested, QA/DanielTested, QA/Passed, Priority/High
